[build]
  base = "frontend"
  command = "npm ci --production=false && npm run build"
  publish = "netlify-build"  # <-- Usa el nombre exacto de tu carpeta generada

[context.production.environment]
  NODE_VERSION = "20.12.2"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200